# Generated by Django 3.2.2 on 2021-05-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
